package ru.eetk.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color

// Light Colors
internal val primaryLight = Color(0xFF8F4B39)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFDBD1)
internal val onPrimaryContainerLight = Color(0xFF3A0A01)
internal val secondaryLight = Color(0xFF77574E)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFFFDBD1)
internal val onSecondaryContainerLight = Color(0xFF2C150F)
internal val tertiaryLight = Color(0xFF6C5D2E)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFF6E1A6)
internal val onTertiaryContainerLight = Color(0xFF231B00)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFFFF8F6)
internal val onBackgroundLight = Color(0xFF231917)
internal val surfaceLight = Color(0xFFFFF8F6)
internal val onSurfaceLight = Color(0xFF231917)
internal val surfaceVariantLight = Color(0xFFF5DED8)
internal val onSurfaceVariantLight = Color(0xFF53433F)
internal val outlineLight = Color(0xFF85736E)
internal val outlineVariantLight = Color(0xFFD8C2BC)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF392E2B)
internal val inverseOnSurfaceLight = Color(0xFFFFEDE9)
internal val inversePrimaryLight = Color(0xFFFFB5A1)
internal val surfaceDimLight = Color(0xFFE8D6D2)
internal val surfaceBrightLight = Color(0xFFFFF8F6)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFFFF1ED)
internal val surfaceContainerLight = Color(0xFFFCEAE5)
internal val surfaceContainerHighLight = Color(0xFFF7E4E0)
internal val surfaceContainerHighestLight = Color(0xFFF1DFDA)

// Dark Colors
internal val primaryDark = Color(0xFFFFB5A1)
internal val onPrimaryDark = Color(0xFF561F10)
internal val primaryContainerDark = Color(0xFF723524)
internal val onPrimaryContainerDark = Color(0xFFFFDBD1)
internal val secondaryDark = Color(0xFFE7BDB2)
internal val onSecondaryDark = Color(0xFF442A23)
internal val secondaryContainerDark = Color(0xFF5D4038)
internal val onSecondaryContainerDark = Color(0xFFFFDBD1)
internal val tertiaryDark = Color(0xFFD9C58D)
internal val onTertiaryDark = Color(0xFF3B2F05)
internal val tertiaryContainerDark = Color(0xFF534619)
internal val onTertiaryContainerDark = Color(0xFFF6E1A6)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF1A110F)
internal val onBackgroundDark = Color(0xFFF1DFDA)
internal val surfaceDark = Color(0xFF1A110F)
internal val onSurfaceDark = Color(0xFFF1DFDA)
internal val surfaceVariantDark = Color(0xFF53433F)
internal val onSurfaceVariantDark = Color(0xFFD8C2BC)
internal val outlineDark = Color(0xFFA08C88)
internal val outlineVariantDark = Color(0xFF53433F)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFF1DFDA)
internal val inverseOnSurfaceDark = Color(0xFF392E2B)
internal val inversePrimaryDark = Color(0xFF8F4B39)
internal val surfaceDimDark = Color(0xFF1A110F)
internal val surfaceBrightDark = Color(0xFF423734)
internal val surfaceContainerLowestDark = Color(0xFF140C0A)
internal val surfaceContainerLowDark = Color(0xFF231917)
internal val surfaceContainerDark = Color(0xFF271D1B)
internal val surfaceContainerHighDark = Color(0xFF322825)
internal val surfaceContainerHighestDark = Color(0xFF3D3230)


